### ISSUE TITLE
symbol(s) not found for architecture i386

### ISSUE THREAD

**Issue by Arryboom** [rablwupei/CryptoPP-for-iOS#1]
Hi Thanks for your hard work here,But when I follow your direction compiled cryptopp and then import demo xcode project to build I got error below:
![xxxxxwwwwww](https://user-images.githubusercontent.com/28295452/43626210-784fe8dc-9723-11e8-8fec-3319ee241476.png)

ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Is there any missing part?

**Comment by rablwupei** [comment]
I tried this project, but I can't correct it. There are other compilation problems. sorry.
